{% set name = "gridmet_bmi" %}
{% set version = "0.2.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/csdms-contrib/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 91b369d38c523f419954a9cdb7e38b0ad0d28df91f6578355cd911b0f0947dd7

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - bmipy
    - click
    - numpy
    - pyyaml
    - requests
    - netcdf4
    - xarray

test:
  requires:
    - python ={{ python_min }}
    - bmi-tester
  imports:
    - gridmet_bmi
  source_files:
    - examples
  commands:
    - bmi-test gridmet_bmi.bmi_gridmet:BmiGridmet --config-file=${PWD}/examples/gridmet_bmi.yaml --root-dir=examples -vvv

about:
  home: https://github.com/nhm-usgs/{{ name }}
  license: CC0-1.0
  license_file: LICENSE.md
  summary: Fetch gridMET meteorological data
  description: |
    gridmet_bmi is a Python package to fetch and cache gridMET
    <http://www.climatologylab.org/gridmet.html> meteorological
    data. It includes a command-line interface, as well as a Basic
    Model Interface (BMI) <https://bmi.readthedocs.io> for coupling
    with models as a data service.
  dev_url: https://github.com/csdms-contrib/{{ name }}

extra:
  recipe-maintainers:
    - rmcd-mscb
    - mdpiper
